### ISSUE TITLE
Issue with parsing session including MongoId

### ISSUE THREAD

**Issue by joawan** [mscdex/groan#2]
Hello,

I'm trying to use groan in a project and have an issue parsing the session data.
The session data contains a MongoId, which seems to fool the parser.

See this:
flash|a:2:{s:5:"email";s:19:"myemail@example.com";s:6:"events";a:1:{i:0;a:3:{s:9:"client_id";s:24:"4d00e8d6bf92fc8648000000";s:7:"user_id";s:6:"100003";s:3:"_id";C:7:"MongoId":24:{513f412ee77dddfb75000006}}}}user|a:1:{s:7:"user_id";s:6:"100003";}

This is a "valid" generate session from PHP when adding a MongoId to the session.
When reading session with groan, the key for the 'user' object is not 'user', it is 'MongoId":24:{513f412ee77dddfb75000006}}}}user'

Seems groan is not handling the serialization of MongoId properly.
See: http://php.net/manual/en/class.mongoid.php

MongoIds are serializable/unserializable. Their serialized form is similar to their string form:
C:7:"MongoId":24:{4af9f23d8ead0e1d32000000}

**Comment by mscdex** [comment]
Fixed in 73ff7ae. Let me know if that works for you.

**Comment by joawan** [comment]
It works beautifully!
Thanks!

Will you publish the fix to npm?

**Comment by mscdex** [comment]
Done.
