### ISSUE TITLE
Unescaped quotes in a string causes a infinite loop

### ISSUE THREAD

**Issue by mikael-lindstrom** [mscdex/groan#3]
Hi,

We have been using groan for a node.js project and have discovered a problem. If we try to parse a php session that have a unescaped string groan enters a infinite loop. For example:

PHParse("session|s:44:\"A test string containing \"unescaped\" quotes\"");

will never return a value. This is of course a problem with our sessions and we have changed it to always have escaped strings but it is never the less dangerous since node.js will stop responding.

**Comment by mscdex** [comment]
Fixed in a7e76b2. Thanks, I'm not sure why I wasn't using the given string length for parsing....

**Comment by mikael-lindstrom** [comment]
Thanks for the quick fix!

I think I know why you didn't use the given length, apparently php specifies the length in bytes and not in characters. This means that if you use UTF-8 and use a non-ascii character it will be two bytes and the length will not match the number of characters. In node.js this should be solvable with use of the Buffer class but it seems a bit more tricky in browsers.
