### ISSUE TITLE
UTF8 chars in php session

### ISSUE THREAD

**Issue by btamas** [mscdex/groan#5]
I have a php session like that:

``` javascript
lastname|s:7:"Miklós";firstname|s:10:"Szörényi";gender|s:1:"1";
```

When groan parse it, I get this:

``` javascript
{ lastname: 'Miklós"', irstname: 'Szörényi";', nder: '1' }
```

The reason of parsing failure is the wrong length of the string value. The length of "Miklós" is 6, but the default php serialization say it's 7, because of the UTF chars.

**Comment by mscdex** [comment]
Please check the master branch now, this should be fixed now.

**Comment by btamas** [comment]
It's working right now. Thanks.
